### ISSUE TITLE
how does one build the mvn jar file? 

### ISSUE THREAD

**Issue by kmacpher67** [psi09/psi09-philips-assignment#4]
Having trouble getting the mvn build to work. 
tried a few iterations. sorry gradle guy not mvn, 
mvn has troubled me as much as ant over the years. 
it's me not you. 

thanks for the effort.

**Comment by kmacpher67** [comment]
mvn install
```
ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.856 s <<< FAILURE! - in com.philips.controller.PetControllerTests
[ERROR] noParamGreetingShouldReturnDefaultMessage  Time elapsed: 0.261 s  <<< FAILURE!
java.lang.AssertionError: Status expected:<200> but was:<404>
        at com.philips.controller.PetControllerTests.noParamGreetingShouldReturnDefaultMessage(PetControllerTests.java:42)

[ERROR] paramGreetingShouldReturnTailoredMessage  Time elapsed: 0.01 s  <<< FAILURE!
java.lang.AssertionError: Status expected:<200> but was:<404>
        at com.philips.controller.PetControllerTests.paramGreetingShouldReturnTailoredMessage(PetControllerTests.java:50)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   PetControllerTests.noParamGreetingShouldReturnDefaultMessage:42 Status expected:<200> but was:<404>
[ERROR]   PetControllerTests.paramGreetingShouldReturnTailoredMessage:50 Status expected:<200> but was:<404>
[INFO] 
[ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0

```

**Comment by psi09** [comment]
@kmacpher67 , you can use mvn clean install -DskipTests to skip test and run application...
if you want me to fix it let me know.

**Comment by psi09** [comment]
for testing ...
http://localhost:8080/petgreeting/?name=SpringCommunity
http://localhost:8080/petgreeting

**Comment by psi09** [comment]
@kmacpher67  issue fixed.."mvn clean install"
closing the issue..
